info:
  contact: {}
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 创建用户
      tags:
      - 用户模块
swagger: "2.0"
